apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mywebapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "kubernetes.adoki.hadoop.local"
    http:
      paths:
      - path: /mywebapp
        pathType: Prefix
        backend:
          service:
            name: mywebapp
            port:
              number: 80
